package rules.EventMessage.EventFired_dir
uses gw.plugin.integration.InitializableClientSystemTransport
uses gw.plugin.Plugins

@gw.rules.RuleName("ClaimCenter")
internal class ClaimCenter {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 71
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
