package rules.EventMessage.EventFired_dir
uses gw.plugin.Plugins
uses gw.plugin.integration.InitializableClientSystemTransport

@gw.rules.RuleName("PolicyCenter")
internal class PolicyCenter {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 70
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
