package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Safe Ordering Demo")
internal class SafeOrderingDemo {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 20

/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
